--*************************************************
--***** ZERO NET AMOUNT IN LEDGER HEADER
--*************************************************
SELECT TRN_LEDGER_HEADER.LEDGER_HEADER_ID         AS LEDGER_HEADER_ID,
       MST_CUSTOMER.CERTIFICATE_NO                AS CERTIFICATE_NO,
       TRN_LEDGER_HEADER.LEDGER_DATE              AS LEDGER_DATE,
       TRN_LEDGER_HEADER.TRAN_TYPE                AS TRAN_TYPE,
       TRN_LEDGER_HEADER.SUB_TYPE                 AS SUB_TYPE,
       TRN_LEDGER_HEADER.RECEIPT_NO               AS RECEIPT_NO,
       TRN_LEDGER_HEADER.NET_AMOUNT               AS NET_AMOUNT,
       'NET AMOUNT ZERO IN THE TRN_LEDGER_HEADER' AS REMARKS
FROM   TRN_LEDGER_HEADER,
       MST_CUSTOMER
WHERE  TRN_LEDGER_HEADER.CUSTOMER_ID       = MST_CUSTOMER.CUSTOMER_ID
AND    TRN_LEDGER_HEADER.OPENING_FLAG      = 0
AND    TRN_LEDGER_HEADER.CANCELLATION_FLAG = 0
AND    TRN_LEDGER_HEADER.NET_AMOUNT        = 0

--
--SELECT * FROM TRN_LEDGER_HEADER
--WHERE LEDGER_HEADER_ID = 710198   -- 10000.00
--
--UPDATE TRN_LEDGER_HEADER
--SET NET_AMOUNT = 0
--WHERE  LEDGER_HEADER_ID = 710198

--*************************************************
--***** NO DETAILS FOR LEDGER_HEADER
--*************************************************
SELECT TRN_LEDGER_HEADER.LEDGER_HEADER_ID                      AS LEDGER_HEADER_ID,
       MST_CUSTOMER.CERTIFICATE_NO                             AS CERTIFICATE_NO,
       TRN_LEDGER_HEADER.LEDGER_DATE                           AS LEDGER_DATE,
       TRN_LEDGER_HEADER.TRAN_TYPE                             AS TRAN_TYPE,
       TRN_LEDGER_HEADER.SUB_TYPE                              AS SUB_TYPE,
       TRN_LEDGER_HEADER.RECEIPT_NO                            AS RECEIPT_NO,
       TRN_LEDGER_HEADER.NET_AMOUNT                            AS NET_AMOUNT,
      'NO DETAIL RECORDS IN TRN_LEDGER_DETAIL FOR THE RECORDS' AS REMARKS
FROM   TRN_LEDGER_HEADER,
       MST_CUSTOMER
WHERE  TRN_LEDGER_HEADER.CUSTOMER_ID       = MST_CUSTOMER.CUSTOMER_ID
AND    LEDGER_HEADER_ID NOT IN (SELECT LEDGER_HEADER_ID FROM TRN_LEDGER_DETAIL)
AND    TRN_LEDGER_HEADER.CANCELLATION_FLAG = 0
AND    TRN_LEDGER_HEADER.OPENING_FLAG      = 0
ORDER BY TRN_LEDGER_HEADER.LEDGER_DATE,
         TRN_LEDGER_HEADER.LEDGER_HEADER_ID


--*************************************************
--***** NO CUSTOMER ID IN LEDGER HEADER
--*************************************************
SELECT TRN_LEDGER_HEADER.LEDGER_HEADER_ID                 AS LEDGER_HEADER_ID,
       ''                                                 AS CERTIFICATE_NO,
       TRN_LEDGER_HEADER.LEDGER_DATE                      AS LEDGER_DATE,
       TRN_LEDGER_HEADER.TRAN_TYPE                        AS TRAN_TYPE,
       TRN_LEDGER_HEADER.SUB_TYPE                         AS SUB_TYPE,
       TRN_LEDGER_HEADER.RECEIPT_NO                       AS RECEIPT_NO,
       TRN_LEDGER_HEADER.NET_AMOUNT                       AS NET_AMOUNT,
       'CUSTOMER ID NOT PRESENT IN THE TRN_LEDGER_HEADER' AS REMARKS
FROM   TRN_LEDGER_HEADER
WHERE  TRN_LEDGER_HEADER.OPENING_FLAG      = 0
AND    TRN_LEDGER_HEADER.CANCELLATION_FLAG = 0
AND    TRN_LEDGER_HEADER.CUSTOMER_ID       = 0
AND    TRN_LEDGER_HEADER.TRAN_TYPE        <> 'IF'

--SELECT * FROM TRN_LEDGER_HEADER WHERE LEDGER_HEADER_ID = 710193   -- 622642
--UPDATE TRN_LEDGER_HEADER
--SET CUSTOMER_ID = 0
--WHERE LEDGER_HEADER_ID = 710193

--SELECT * FROM TRN_LEDGER_HEADER WHERE LEDGER_HEADER_ID = 710207   --   729441
--UPDATE TRN_LEDGER_HEADER
--SET CUSTOMER_ID = 0
--WHERE LEDGER_HEADER_ID = 710207

--*********************************************************
--*** CUSTOMER DETAIL ID NOT UPDATED IN LEDGER_dETAIL
--*********************************************************
--SELECT TRN_LEDGER_DETAIL.* 
--FROM TRN_LEDGER_DETAIL,
--     TRN_LEDGER_HEADER
--WHERE TRN_LEDGER_DETAIL.LEDGER_HEADER_ID = TRN_LEDGER_HEADER.LEDGER_HEADER_ID
--AND TRN_LEDGER_HEADER.TRAN_TYPE = 'MPS'
--AND TRN_LEDGER_HEADER.OPENING_FLAG = 0
--AND TRN_LEDGER_HEADER.CANCELLATION_FLAG = 0
--AND TRN_LEDGER_DETAIL.CUSTOMER_DETAIL_ID = 0


SELECT TRN_LEDGER_HEADER.LEDGER_HEADER_ID                    AS LEDGER_HEADER_ID,
       MST_CUSTOMER.CERTIFICATE_NO                           AS CERTIFICATE_NO,
       TRN_LEDGER_HEADER.LEDGER_DATE                         AS LEDGER_DATE,
       TRN_LEDGER_HEADER.TRAN_TYPE                           AS TRAN_TYPE,
       TRN_LEDGER_HEADER.SUB_TYPE                            AS SUB_TYPE,
       TRN_LEDGER_HEADER.RECEIPT_NO                          AS RECEIPT_NO,
       TRN_LEDGER_HEADER.NET_AMOUNT                          AS RECEIPT_NO,
       'CUSTOMER DETAIL ID NOT PRESENT IN TRN_LEDGER_DETAIL' AS REMARKS
FROM   TRN_LEDGER_DETAIL,
       TRN_LEDGER_HEADER,
       MST_CUSTOMER
WHERE  TRN_LEDGER_DETAIL.LEDGER_HEADER_ID   = TRN_LEDGER_HEADER.LEDGER_HEADER_ID
AND    TRN_LEDGER_HEADER.CUSTOMER_ID        = MST_CUSTOMER.CUSTOMER_ID 
AND    TRN_LEDGER_HEADER.TRAN_TYPE          = 'MPS'
AND    TRN_LEDGER_HEADER.OPENING_FLAG       = 0
AND    TRN_LEDGER_HEADER.CANCELLATION_FLAG  = 0
AND    TRN_LEDGER_DETAIL.CUSTOMER_DETAIL_ID = 0

--SELECT * FROM MST_CUSTOMER_DETAIL WHERE CUSTOMER_ID = 0

--
--896869 ldid
--2656009 customerdeid
--
--select * from trn_ledger_detail where ledger_detail_id = 896869
----
--update trn_ledger_detail
--set customer_detail_id = 0
--where  ledger_detail_id = 896869
